services:
#    tranz_bma_user_order.example:
#        class: Tranz\BMAUserOrderBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    tranzbmauserorderbundle.advuserorder.service:
        class: Tranz\BMAUserOrderBundle\Service\AdvUserOrderService
        arguments: ["@doctrine.orm.entity_manager", 'Tranz\BMAUserOrderBundle\Entity\AdvUserOrder', "@translator.default"]